# 全局配置
readRecord = "TOML读取成功"

# 应用信息
[app]
    author = "付鹏篚"
    info = "笔记"
    mark = "第一行\n第二行."            # 换行
    release = 2020-09-09              # 时间


#配置MySQL连接参数
[mysqlLink]
    username = "root"  #账号
    password = "root" #密码
    host = "127.0.0.1" #数据库地址，可以是Ip或者域名
    port = 3306 #数据库端口
    Dbname = "noteProject" #数据库名
    timeout = "10s" #连接超时，10秒
[logFile]
    LOG_ROUTER_PATH="logFile/logs"
    File_Name="LogFile"
[jsonwebtoken]
    jwtSecret="newbie"